# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
#added credentials
#updated credentials 7
#added publish profile 
#added enable oryx build
#cleaned up kudu files
#made new web app
#del some files 
name: Build and deploy Node.js app to Azure Web App - keychamp

on:
  push:
    branches:
      - ok
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    jobs:
      build:
        runs-on: windows-latest
        steps:
        - uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

        - uses: actions/checkout@v2
          with:
           lfs: true

        - name: Set up Node.js version
          uses: actions/setup-node@v1
          with:
            node-version: '18.x'


        - name: npm install sqlite3
          run: npm install sqlite3
          working-directory: './nf'

        - name: npm install fastify-sqlite
          run: npm install fastify-sqlite
          working-directory: './nf'

        - name: npm install
          run: npm install
          working-directory: './nf'

        - name: npm rebuild
          run: npm rebuild
          working-directory: './nf'

        - name: npm build
          run: |
            npm run build --if-present
            npm run test --if-present
          working-directory: './nf'

        - name: Upload artifact for deployment job
          uses: actions/upload-artifact@v2
          with:
            name: node-app
            path: .

    deploy:
      runs-on: windows-latest
      needs: build
      environment:
        name: 'production'
        url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

      steps:
        - name: Azure Login
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

        - name: Download artifact from build job
          uses: actions/download-artifact@v2
          with:
            name: node-app

        - name: 'Deploy to Azure Web App'
          uses: azure/webapps-deploy@v2
          id: deploy-to-webapp
          with:
            app-name: 'keychamp'
            slot-name: 'production'
            publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
            package: .
        # - name: Start the app
        #   run: npm start        #   working-directory: './nf'

